### ISSUE TITLE
Problem with http-interop provided as dev dependency

### ISSUE THREAD

**Issue by belgattitude** [webimpress/composer-extra-dependency#5]
@webimpress, 

From the doc 

>  If dependency is already provided in user composer.json the plugin is not going to do anything.

I got some problem when my http-interop dep is set as dev dependency (require-dev). It was not considered, so I got prompted to enter the http-interop version (which adds the ^0.5 in require, dev having ^0.4.1). 

```json
{
  "name": "package/name",
  "require": {
    "webimpress/http-middleware-compatibility": "^0.1 || ^1.0"
  },
  "require-dev" : {
    "http-interop/http-middleware": "^0.4.1",
    "zendframework/zend-expressive": "^2.0.5",
    "zendframework/zend-expressive-fastroute": "^2.0",
    "zendframework/zend-expressive-helpers": "^4.2.0",
    "zendframework/zend-expressive-twigrenderer": "^1.4.0",
    "zendframework/zend-servicemanager": "^3.3",
  }
}
```

Note: I added http-interop as dev because it's only used for smoke tests (I do them with expressive - ex https://github.com/belgattitude/soluble-wallit)

**Comment by michalbundyra** [comment]
Resolved in  0f315da, it's going to be released in 0.2.2 soon. Thanks @belgattitude !
